### ISSUE TITLE
Hypixel Skyblock Wiki kindly asks for a .jar file

### ISSUE THREAD

**Issue by joker876** [MichaelPriebe/wikitools#1]
Hello!
I am joker876, an admin and a bureaucrat on Hypixel Skyblock Wiki on Fandom.
We are currently in high need of various images, ranging from mobs to armor sets. 
I, in the name of all editors, am kindly asking you to share the .jar file with us. 
If you don't want to, we will understand. However, if you decided to share your awesome mod with us, we would be forever grateful.

Thanks in advance,
joker876

**Comment by mikuhl-dev** [comment]
Sorry I might have missed this message. You should be able to build it very easily with IntelliJ or Eclipse.

**Comment by joker876** [comment]
Am I allowed to share this mod with other wiki editors?

**Comment by mikuhl-dev** [comment]
That's what it was made for.

**Comment by joker876** [comment]
We are having some big troubles with building it; can you just send us the .jar file?

**Comment by joker876** [comment]
Um, hello?

**Comment by mikuhl-dev** [comment]
Whats the problem?

**Comment by joker876** [comment]
I was not responsible for trying to build this mod, as I have absolutely 0 experience with minecraft mods or java in general; other editor was doing this, they said they were having some system issues.
Please just make the .jar file and send it to us, it will save both us and you a lot of time.

**Comment by joker876** [comment]
Knock knock...

**Comment by mikuhl-dev** [comment]
What error did they get when building it?

**Comment by joker876** [comment]
I don't know, they did not tell me. What they did tell me is that they hate using Eclipse, for some reason. 
Again, please just give us the mod, you have a million times more experience with it, know exactly how to build it, and maybe even still have it in your mods folder.
If you cannot give us the .jar file for whatever reason, just say it.

**Comment by joker876** [comment]
Hello?

**Comment by joker876** [comment]
Hey,
I hope you are going to read this. We have tried many different things in order to build this mod, but we didn't succeed.
We want to ask you one thing: can you build this mod and send us the .jar file? We really need it.

P.S. If you don't respond within the next 3 days I am going to send a message on your other project. This is very important to us.

Best regards,
Hypixel Skyblock Wiki Team,
represented by joker876.

**Comment by mikuhl-dev** [comment]
Check artifacts here: https://github.com/MichaelPriebe/wikitools/runs/1140504330
